# Generated by Django 4.2.3 on 2023-07-14 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=50)),
                ('line', models.CharField(max_length=50)),
                ('transfer_available', models.JSONField()),
            ],
        ),
    ]
