# Generated by Django 4.2.3 on 2023-07-31 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_id', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('direction', models.CharField(max_length=50)),
                ('line', models.IntegerField()),
                ('transfer_available', models.JSONField(default=list)),
                ('accessibility_information', models.TextField(blank=True, null=True)),
                ('POI_locator', models.TextField(blank=True, null=True)),
                ('next_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openapi_seoul_service.subwaystation')),
            ],
            options={
                'unique_together': {('station_id', 'direction')},
            },
        ),
    ]
