# Generated by Django 4.2.3 on 2023-07-31 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi_seoul_service', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubwayStationInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('accessibility_information', models.TextField(blank=True, null=True)),
                ('POI_locator', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
