# Generated by Django 4.2.3 on 2023-07-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi_seoul_service', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subwaystation',
            name='next_station',
            field=models.CharField(default='', max_length=100),
        ),
    ]
