# Generated by Django 4.2.3 on 2023-07-16 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi_seoul_service', '0003_subwaystation_station_id_alter_subwaystation_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransferLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_id', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='subwaystation',
            name='line',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='subwaystation',
            name='station_id',
            field=models.IntegerField(),
        ),
        migrations.RemoveField(
            model_name='subwaystation',
            name='transfer_available',
        ),
        migrations.AddField(
            model_name='subwaystation',
            name='transfer_available',
            field=models.ManyToManyField(to='openapi_seoul_service.transferline'),
        ),
    ]
