# Generated by Django 4.2.3 on 2023-07-16 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi_seoul_service', '0004_transferline_alter_subwaystation_line_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subwaystation',
            name='transfer_available',
        ),
        migrations.DeleteModel(
            name='TransferLine',
        ),
        migrations.AddField(
            model_name='subwaystation',
            name='transfer_available',
            field=models.JSONField(default=''),
        ),
    ]
