# Generated by Django 4.2.3 on 2023-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('openapi_seoul_service', '0005_remove_subwaystation_transfer_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaystation',
            name='transfer_available',
            field=models.JSONField(default=list),
        ),
    ]
