# Generated by Django 4.2.3 on 2023-07-16 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('openapi_seoul_service', '0006_alter_subwaystation_transfer_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subwaystation',
            name='next_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='openapi_seoul_service.subwaystation'),
        ),
    ]
