beta_settings:
    cloud_sql_instances: ig004-394806:asia-northeast3:psql-ee95

runtime: python
env: flex
entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker django_server.asgi:application

runtime_config:
  python_version: 3.7
