runtime: python
env: flex

entrypoint: uvicorn django_server.asgi:application --host 0.0.0.0 --port 8080

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1

runtime_config:
  python_version: 3.10

network:
  forwarded_ports:
  - 8080/tcp
